#!/bin/bash

# Set the Maven version
MAVEN_VERSION="3.9.8"

# Install prerequisites
sudo apt-get update
sudo apt-get install default-jdk wget unzip vim -y

# Download and extract Maven
sudo wget https://dlcdn.apache.org/maven/maven-3/$MAVEN_VERSION/binaries/apache-maven-$MAVEN_VERSION-bin.zip
sudo unzip apache-maven-$MAVEN_VERSION-bin.zip
sudo rm -rf apache-maven-$MAVEN_VERSION-bin.zip
sudo mv apache-maven-$MAVEN_VERSION /opt/maven

# Set Maven environment variables
sudo echo "export MAVEN_HOME=/opt/maven" >> /etc/profile.d/maven.sh
sudo echo "export PATH=\${MAVEN_HOME}/bin:\${PATH}" >> /etc/profile.d/maven.sh
sudo chmod +x /etc/profile.d/maven.sh
sudo source /etc/profile.d/maven.sh
